### ISSUE TITLE
Change the name of the main.nf file to clarify how to run the pipeline

### ISSUE THREAD

**Issue by nitzcovich** [nf-core/phaseimpute#13]
### Description of feature

It's not a good practice to have two main.nf scripts. It is better to name the main workflow as **phaseinput.nf**

**Comment by LouisLeNezet** [comment]
I'm not sure about that.
The recent change in the template aim for modularity even at the pipeline level.
Therefore from what I understood, pipeline as well as subworkflows need to be organised the same ways as modules inside a folder corresponding to their name and in a main.nf

**Comment by LouisLeNezet** [comment]
Unfortunately for the moment there isn't a lot of pipeline who did the move to the new template.

**Comment by nitzcovich** [comment]
Thanks for your answer, I was not fully aware of the new template, I'll definitely review it.
