### ISSUE TITLE
It's not clear which values are used to defined the input parameters in the main.nf script

### ISSUE THREAD

**Issue by nitzcovich** [nf-core/phaseimpute#14]
### Description of feature

The main workflow takes 6 parameters as inputs: **ch_input, ch_fasta, ch_panel, ch_region, ch_map, and ch_versions**. These variables are not defined with value using params.

**Comment by LouisLeNezet** [comment]
That's normal, those channels are now initialized in the PIPELINE_INTIALISATION() subworkflow with the new template.

**Comment by nitzcovich** [comment]
Perfect, good to know. Thanks for the clarification.
