### ISSUE TITLE
Type not supported: class org.codehaus.groovy.runtime.GStringImpl

### ISSUE THREAD

**Issue by LouisLeNezet** [nf-core/phaseimpute#141]
### Description of the bug

When running the following command the pipeline crash

### Command used and terminal output

nextflow run main.nf --input tests/csv/sample_bam.csv --steps panelprep,impute --outdir results --genome GRCh38 --input_region tests/csv/region.csv -profile singularity --tools glimpse1 --panel tests/csv/panel.csv

Type not supported: class org.codehaus.groovy.runtime.GStringImpl
ERROR ~ Pipeline failed. Please refer to troubleshooting docs: https://nf-co.re/docs/usage/troubleshooting

**Comment by atrigila** [comment]
I tried this and I was not able to reproduce this error.
