### ISSUE TITLE
Error: Panel index file requirement - Invalid filename format and missing file extension

### ISSUE THREAD

**Issue by atrigila** [nf-core/phaseimpute#21]
### Description of the bug

The `schema_input_panel.json` required that  the "`panel index file  cannot contain spaces and must have extension '.vcf' or '.bcf' with '.csi' or '.tbi' extension`". However, 1000G index files, such as s3://1000genomes/release/20130502/ALL.chr20.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz.tbi
end with extension `vcf.gz.tbi`

Solution:

```
            "index": {
                "type": "string",
                "pattern": "^\\S+\\.(vcf|bcf)(\\.gz)?\\.(tbi|csi)$",
                "errorMessage": "Panel index file must be provided, cannot contain spaces and must have extension '.vcf' or '.bcf' with optional '.gz' extension and with '.csi' or '.tbi' extension"
            }
```

**Comment by LouisLeNezet** [comment]
That's effectively a mistake from me.
Are you working on it or do you want me to update it ?
