### ISSUE TITLE
error with --step simulate,impute and --tools stitch

### ISSUE THREAD

**Issue by atrigila** [nf-core/phaseimpute#61]
### Description of the bug

Running both `--step simulate,impute` and `--tools stitch` raises an error regarding extensions. However, all the input files have the same extension. 

### Command used and terminal output

```console
nextflow run phaseimpute -profile test_stitch,docker --outdir test_stitch --step simulate,impute

Region file provided as input is a csv file
Impute with STITCH
Extensions: []
All input files must have the same extension
ERROR ~ Pipeline failed. Please refer to troubleshooting docs: https://nf-co.re/docs/usage/troubleshooting

 -- Check '.nextflow.log' file for details
-[nf-core/phaseimpute] Pipeline completed with errors-
```

### Relevant files

`input        = "${projectDir}/tests/csv/sample_bam.csv"`

**Comment by LouisLeNezet** [comment]
This was due to the ordering of the input channel in the `NFCORE_PHASEIMPUTE` workflow.
