### ISSUE TITLE
add validation for stitch

### ISSUE THREAD

**Issue by atrigila** [nf-core/phaseimpute#64]
### Description of feature

STITCH uses all samples to impute. Unlike other tools, it produces a single, multisample, imputed VCF. To use GLIMPSE2 concordance, individual samples need to be compared against individual truth VCF. We need to think a method to validate imputation via STITCH.

**Comment by LouisLeNezet** [comment]
Hi, @atrigila 

There is two way to do this:
- Keep stitch output as GVCF and merge the truth file in a similar GVCF
- Separate the output of stitch in individuals VCF (same as other imputation tools)

I would personally be in favour of the second one to uniformise the output file across imputation software.
I will add a PR regarding that.
