### ISSUE TITLE
chr check does not work on dog datasets

### ISSUE THREAD

**Issue by atrigila** [nf-core/phaseimpute#98]
### Description of the bug

Working on a dog dataset I have encountered an issue with the chromosome check functionality. The chr check assumes that all VCF files will contain a header matching the regular expression ^##contig=<ID=([^,>]*). However, it appears that this header format is not standard across all VCF files.

According to the VCF specifications, the contig tag is recommended but not mandatory, as detailed in the VCF v4.1 specifications: [VCF v4.1 PDF](http://samtools.github.io/hts-specs/VCFv4.1.pdf).

Proposed Solution

Implement a more flexible chr check that does not solely rely on the ##contig header format. This GitHub [vcfverifier by cmdcolin](https://github.com/cmdcolin/vcfverifier) repository checks a VCF against a FASTA file and written in Rust. Apparently it processes chromosome 1 (6.5 million rows) of the 1000 Genomes dataset in approximately 24 seconds. We can add this tool to `nf-core` and then integrate it into `phaseimpute`.

### Command used and terminal output

```console
nextflow run phaseimpute -profile test_dog_panelprep,singularity --outdir test_dog
```

### Relevant files

Dog test datasets in `nf-core test-datasets`:

```
    fasta        = params.pipelines_testdata_base_path + "panel/dog/canFam3.fa"
    panel        = params.pipelines_testdata_base_path + "panel/dog/dog_panel.csv"
```

**Comment by LouisLeNezet** [comment]
I think the failure of the megatest is separated from this one.
The error for the dog dataset is that the contig comment is absent from the head of the vcf.
This should now be resolved with the PR #102.

Concerning the failure of the full dataset it seems that the igenome fasta reference contigs that are not present in the reference panel that we give to the pipeline.
Is the reference genome used for the alignment of the panel available somewhere ?
